[project]
name = "owlbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nadeem Zaidi", email = "nadeem.zaidi0021@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "grpcio>=1.83.1",
    "grpcio-tools>=1.83.1",
    "markitdown[pdf]>=0.1.7",
]

[project.scripts]
owlbot = "owlbot:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
